version: "3.7"
services:
  elk:
    image: sebp/elk:761
    ports:
      - "5601:5601"
      - "9200:9200"
    environment:
      LOGSTASH_START: 0
  api:
    build: ./rest
    ports:
      - "8080:8080"
