# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from parser_api.models.base_model_ import Model
from parser_api import util


class Doc(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, index: str=None, body: str=None, exec_time: float=None, timestamp: str=None):  # noqa: E501
        """Doc - a model defined in Swagger

        :param index: The index of this Doc.  # noqa: E501
        :type index: str
        :param body: The body of this Doc.  # noqa: E501
        :type body: str
        :param exec_time: The exec_time of this Doc.  # noqa: E501
        :type exec_time: float
        :param timestamp: The timestamp of this Doc.  # noqa: E501
        :type timestamp: str
        """
        self.swagger_types = {
            'index': str,
            'body': str,
            'exec_time': float,
            'timestamp': str
        }

        self.attribute_map = {
            'index': 'index',
            'body': 'body',
            'exec_time': 'exec_time',
            'timestamp': 'timestamp'
        }

        self._index = index
        self._body = body
        self._exec_time = exec_time
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'Doc':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Doc of this Doc.  # noqa: E501
        :rtype: Doc
        """
        return util.deserialize_model(dikt, cls)

    @property
    def index(self) -> str:
        """Gets the index of this Doc.


        :return: The index of this Doc.
        :rtype: str
        """
        return self._index

    @index.setter
    def index(self, index: str):
        """Sets the index of this Doc.


        :param index: The index of this Doc.
        :type index: str
        """
        if index is None:
            raise ValueError("Invalid value for `index`, must not be `None`")  # noqa: E501

        self._index = index

    @property
    def body(self) -> str:
        """Gets the body of this Doc.


        :return: The body of this Doc.
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body: str):
        """Sets the body of this Doc.


        :param body: The body of this Doc.
        :type body: str
        """
        if body is None:
            raise ValueError("Invalid value for `body`, must not be `None`")  # noqa: E501

        self._body = body

    @property
    def exec_time(self) -> float:
        """Gets the exec_time of this Doc.


        :return: The exec_time of this Doc.
        :rtype: float
        """
        return self._exec_time

    @exec_time.setter
    def exec_time(self, exec_time: float):
        """Sets the exec_time of this Doc.


        :param exec_time: The exec_time of this Doc.
        :type exec_time: float
        """

        self._exec_time = exec_time

    @property
    def timestamp(self) -> str:
        """Gets the timestamp of this Doc.


        :return: The timestamp of this Doc.
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: str):
        """Sets the timestamp of this Doc.


        :param timestamp: The timestamp of this Doc.
        :type timestamp: str
        """

        self._timestamp = timestamp
